trigger:
- master
pool:
  name: Azure Pipelines
  vmImage: 'vs2017-win2016'
steps:
  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
    displayName: 'Terraform : PLAN'
    inputs:
      command: plan
