trigger:
- master
pool:
  name: Azure Pipelines
  vmImage: 'vs2017-win2016'
steps:
  - task: Bash@3
    displayName: 'Terraform : PLAN'
    inputs:
      targetType: inline
      script: terraform init
